package space.br1440.platform.tracing.test.arch;

import com.tngtech.archunit.base.DescribedPredicate;
import com.tngtech.archunit.core.domain.JavaMethod;
import com.tngtech.archunit.lang.ArchCondition;
import com.tngtech.archunit.lang.ArchRule;
import com.tngtech.archunit.lang.ConditionEvents;
import com.tngtech.archunit.lang.SimpleConditionEvent;
import lombok.experimental.UtilityClass;

import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.methods;

/**
 * Платформенные правила архитектурной согласованности кода трассировки.
 * <p>
 * Применяются в test-classpath потребительских модулей через {@link ArchRule#check}.
 * Импорт классов выполняется через {@code ClassFileImporter} (стандартный паттерн ArchUnit).
 *
 * <h2>Правила</h2>
 * <ul>
 *   <li>{@link #NO_TRACED_AND_OBSERVED_ON_SAME_METHOD} — запрет одновременной разметки метода
 *       платформенным {@code @Traced} и Micrometer {@code @Observed}: оба создают span,
 *       приводя к double instrumentation. Правило учитывает meta-аннотации
 *       (через {@code areMetaAnnotatedWith}-эквивалент): пользовательский
 *       {@code @CustomObserved}, помеченный {@code @Observed}, тоже считается нарушением (W7).</li>
 * </ul>
 * <p>
 * Slice 1B: правило {@code ESCAPE_HATCH_BUILDERS_REQUIRE_SUPPRESSION} для удалённых v1
 * {@code Facade*SpanBuilder} factory-методов снято; transport governance вернётся с
 * {@code manual().transport()} (Slice 3).
 *
 * <h2>Ограничения, осознанно вне scope</h2>
 * Rule «{@code span handle} обязан использоваться через try-with-resources» (Step 4.3 плана)
 * не реализуется через ArchUnit: ArchUnit работает на bytecode уровня {@code JavaMethodCall}
 * и не различает {@code try-with-resources} statement и ручной {@code try { ... } finally { close() }}
 * (compiler-generated bytecode идентичен). AST-проверка через ArchUnit недоступна; для этого
 * правила backlog предусматривает PMD/SpotBugs custom rule.
 */
@UtilityClass
public final class TracingArchRules {

    /**
     * Запрещает одновременное применение {@code @Traced} и {@code @Observed} на одном методе.
     * <p>
     * Проверка учитывает meta-аннотации: метод, помеченный {@code @Traced} и любой кастомной
     * аннотацией, у которой в metadata присутствует {@code @Observed}, тоже считается нарушением.
     */
    public static final ArchRule NO_TRACED_AND_OBSERVED_ON_SAME_METHOD = methods()
            .that(haveBothTracedAndObservedAnnotations())
            .should(neverExist())
            .because("@Traced и @Observed создают span каждый — одновременная разметка приводит "
                    + "к двойной инструментации (double instrumentation). Используйте только одну "
                    + "из аннотаций; обычно — @Traced для бизнес-методов и @Observed для интеграции "
                    + "с Micrometer Observation handlers.")
            // По умолчанию ArchUnit требует хотя бы один матч predicate — иначе rule падает с
            // failOnEmptyShould. В нашем случае «нет нарушителей» — это успех; явно отключаем.
            .allowEmptyShould(true);

    private static DescribedPredicate<JavaMethod> haveBothTracedAndObservedAnnotations() {
        return new DescribedPredicate<>("are annotated with both @Traced and @Observed (incl. meta-annotations)") {
            @Override
            public boolean test(JavaMethod method) {
                boolean hasTraced = method.isAnnotatedWith(TRACED_FQCN)
                        || method.isMetaAnnotatedWith(TRACED_FQCN);
                boolean hasObserved = method.isAnnotatedWith(OBSERVED_FQCN)
                        || method.isMetaAnnotatedWith(OBSERVED_FQCN);
                return hasTraced && hasObserved;
            }
        };
    }

    private static ArchCondition<JavaMethod> neverExist() {
        return new ArchCondition<>("never exist (rule violation)") {
            @Override
            public void check(JavaMethod method, ConditionEvents events) {
                events.add(SimpleConditionEvent.violated(method,
                        "Метод " + method.getFullName() + " помечен и @Traced, и @Observed одновременно — "
                                + "double instrumentation. Оставьте только одну из аннотаций."));
            }
        };
    }

    private static final String TRACED_FQCN = "space.br1440.platform.tracing.api.annotation.Traced";
    private static final String OBSERVED_FQCN = "io.micrometer.observation.annotation.Observed";
}
