spring:
  config:
    activate:
      on-profile: s4-production

platform:
  tracing:
    enabled: true
    sampling:
      enabled: true
    scrubbing:
      enabled: true
    validation:
      enabled: true
      strict: false
